# .streamlit/secrets.toml

[connections.snowflake]
account = "qqjoha"
user = "xxx"
password = "Cyanmyg1"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
